const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const SERVER='havenmc.mangoohost.live', MIN_VERSION='1.17';
const defaults={server:SERVER,profile:'Oyuncu',lang:'tr',auto:false,ram:4096,minecraftDir:'',javaPath:'java',loader:'Vanilla',version:'1.21.1',profiles:{Oyuncu:{version:'1.21.1',loader:'Vanilla',ram:4096,mods:[]}},mods:[],curseKey:''};
let state={...defaults,...JSON.parse(localStorage.havenmc||'{}')}; state.profiles=state.profiles||defaults.profiles; let manifest=[];
const save=()=>localStorage.havenmc=JSON.stringify(state);
function setStatus(text){$('#status').textContent=text} function show(p){$$('.page').forEach(x=>x.classList.toggle('active',x.id===p));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p))} window.show=show;
function filteredVersions(type='all'){return manifest.filter(v=>v.id>=MIN_VERSION||v.id.startsWith('1.17')).filter(v=>type==='all'||v.type===type)}
function fillVersions(){const list=filteredVersions($('#releaseType')?.value||'all'); const opts=list.length?list:([{id:state.version,type:'release'}]); ['#version','#version2'].forEach(id=>$(id).innerHTML=opts.map(v=>`<option value="${v.id}">${v.id} · ${v.type}</option>`).join('')); $('#version').value=state.version;$('#version2').value=state.version;$('#versionStatus').textContent=`${list.length} sürüm listelendi · Son güncelleme: ${new Date().toLocaleTimeString()}`}
async function loadVersions(){try{const r=await fetch('https://piston-meta.mojang.com/mc/game/version_manifest_v2.json');if(!r.ok)throw Error();manifest=(await r.json()).versions||[];fillVersions()}catch(e){manifest=defaults.version?[{id:defaults.version,type:'release'}]:[];fillVersions();$('#versionStatus').textContent='Manifest alınamadı; önbellek kullanılıyor.'}}
function activeProfile(){return state.profiles[state.profile]||state.profiles.Oyuncu}
function applyLanguage(){const en=state.lang==='en';const labels=en?['Home','Versions','Mods','Profiles','Settings']:['Ana Sayfa','Sürümler','Modlar','Profiller','Ayarlar'];$$('.nav span').forEach((x,i)=>x.textContent=labels[i]);$('#title').textContent=en?'Ready to play?':'Oyuna hazır mısın?';$('#onlineText').textContent=en?'SERVER ONLINE':'SUNUCU AKTİF';$('#play').textContent=en?'▶ PLAY':'▶ OYNA';$('#copy').textContent=en?'Copy IP':'IP Kopyala';$('#saveSettings').textContent=en?'Save settings':'Kaydet';document.documentElement.lang=state.lang}
function renderProfiles(){$('#profilesList').innerHTML=Object.entries(state.profiles).map(([name,p])=>`<div class="profileItem"><div><b>${name}</b><small>${p.version||'1.21.1'} · ${p.loader||'Vanilla'} · ${p.ram||4096} MB</small></div><div><button onclick="selectProfile('${name.replaceAll("'","\\'")}')">Seç</button>${name!=='Oyuncu'?`<button class="danger" onclick="deleteProfile('${name.replaceAll("'","\\'")}')">Sil</button>`:''}</div></div>`).join('')}
window.selectProfile=name=>{state.profile=name;const p=activeProfile();state.version=p.version;state.loader=p.loader;refresh();show('home')}; window.deleteProfile=name=>{delete state.profiles[name];state.profile='Oyuncu';refresh()};
function refresh(){const p=activeProfile(); $('#ipSide').textContent=state.server;$('#serverCard').textContent=state.server;$('#serverInput').value=state.server;$('#profileName').textContent=state.profile;$('#avatar').textContent=state.profile[0]?.toUpperCase()||'H';$('#cardProfile').textContent=state.profile;$('#autoSetting').checked=state.auto;$('#autojoin').checked=state.auto;$('#language').value=state.lang;$('#minecraftDir').value=state.minecraftDir;$('#javaPath').value=state.javaPath;$('#ram').value=p.ram||state.ram;$('#curseKey').value=state.curseKey||'';$('#loader').value=p.loader||state.loader;$('#cardLoader').textContent=p.loader||state.loader;applyLanguage();save();renderProfiles();if(manifest.length)fillVersions()}
$('#addProfile').onclick=()=>{const n=$('#newProfile').value.trim();if(!n)return;if(!state.profiles[n])state.profiles[n]={version:state.version,loader:state.loader,ram:+$('#ram').value||4096,mods:[]};state.profile=n;$('#newProfile').value='';refresh()};
$('#copy').onclick=async()=>{await navigator.clipboard?.writeText(state.server);setStatus('Sunucu adresi kopyalandı')}; $('#autojoin').onchange=e=>{state.auto=e.target.checked;refresh()};$('#autoSetting').onchange=e=>state.auto=e.target.checked;
$('#saveSettings').onclick=()=>{state.server=$('#serverInput').value.trim()||SERVER;state.lang=$('#language').value;state.auto=$('#autoSetting').checked;state.minecraftDir=$('#minecraftDir').value.trim();state.javaPath=$('#javaPath').value.trim()||'java';state.ram=+$('#ram').value||4096;state.curseKey=$('#curseKey').value.trim();activeProfile().ram=state.ram;refresh();setStatus(state.lang==='en'?'Settings saved':'Ayarlar kaydedildi')};
$('#useVersion').onclick=()=>{state.version=$('#version2').value;activeProfile().version=state.version;refresh();show('home')};$('#releaseType').onchange=fillVersions;$('#loader').onchange=e=>{state.loader=e.target.value;activeProfile().loader=state.loader;$('#cardLoader').textContent=state.loader;save()};$$('[data-loader]').forEach(b=>b.onclick=()=>{$('#loader').value=b.dataset.loader;$('#loader').dispatchEvent(new Event('change'));});
$('#play').onclick=async()=>{const p=activeProfile();state.version=$('#version').value||p.version;p.version=state.version;p.loader=$('#loader').value;save();setStatus('Başlatma hazırlanıyor…');try{if(window.__TAURI__?.invoke){await window.__TAURI__.invoke('launch_minecraft',{version:p.version,loader:p.loader,ram:p.ram||4096,server:state.server,javaPath:state.javaPath,minecraftDir:state.minecraftDir});setStatus('Minecraft başlatıldı')}else{setStatus('Masaüstü uygulamasında başlatma hazır');alert(`Minecraft başlatma isteği hazır.\nSürüm: ${p.version}\nYükleyici: ${p.loader}\nSunucu: ${state.server}`)}}catch(e){setStatus('Başlatılamadı: '+e)}};
async function searchMods(){const q=$('#modSearch').value.trim()||'minecraft';const source=$('#modSource').value;const box=$('#modResults');box.innerHTML='<p class="empty">Aranıyor…</p>';try{if(source==='curseforge'){if(!state.curseKey){box.innerHTML='<p class="empty">CurseForge araması için Ayarlar bölümüne API anahtarı ekleyin.</p>';return}throw Error('CurseForge API araması anahtar ve endpoint ayarı gerektirir.')}const r=await fetch(`https://api.modrinth.com/v2/search?query=${encodeURIComponent(q)}&limit=12&facets=${encodeURIComponent(JSON.stringify([[`project_type:mod`]]))}`);const data=await r.json();box.innerHTML=(data.hits||[]).map(m=>`<article class="mod"><img src="${m.icon_url||'havenmc-logo.png'}"><div><b>${m.title}</b><small>${m.description||''}</small><button onclick="installMod('${m.project_id}','${m.title.replaceAll("'","\\'")}')">Ekle</button></div></article>`).join('')||'<p class="empty">Sonuç bulunamadı.</p>'}catch(e){box.innerHTML='<p class="empty">Mod araması başarısız oldu. Bağlantınızı kontrol edin.</p>'}}
window.installMod=(id,name)=>{if(!state.mods.some(x=>x.id===id)){state.mods.push({id,name,source:'Modrinth'});activeProfile().mods=state.mods.map(x=>x.id);save();setStatus(`${name} profile eklendi`)}else setStatus('Bu mod zaten ekli')};$('#searchMods').onclick=searchMods;$('#modSearch').onkeydown=e=>e.key==='Enter'&&searchMods();
$$('.nav').forEach(b=>b.onclick=()=>show(b.dataset.page)); document.documentElement.lang=state.lang;refresh();loadVersions();
